import { AIModel, Message } from './types';
import googleLogo from '@/assets/google-logo.svg';
import deepseekLogo from '@/assets/deepseek-logo.svg';
import openaiLogo from '@/assets/openai-logo.svg';
import anthropicLogo from '@/assets/anthropic-logo.svg';
import groqLogo from '@/assets/groq-logo.svg';
import openrouterLogo from '@/assets/openrouter-logo.svg';
import xaiLogo from '@/assets/xai-logo.svg';
import waiLogo from '@/assets/wai-logo.svg';
import inferencenetLogo from '@/assets/inferencenet-logo.svg';
import alibabacloudLogo from '@/assets/alibaba-logo.png';
import nvidiaLogo from '@/assets/nvidia-logo.svg';
export const availableModels: AIModel[] = [
  {
    id: 'deepseek-r1-8b-8bit',
    name: 'deepseek-r1-8b-8bit (w.ai)',
    provider: 'wai',
    description: 'DeepSeek R1 8B 8-bit model',
    maxTokens: 8192,
    thumbnailUrl: waiLogo,
  },
  {
    id: 'meta-llama/llama-3.2-1b-instruct/fp-8',
    name: 'llama-3.2-1b-instruct/fp-8 (inference.net)',
    provider: 'inferencenet',
    description: 'Meta Llama 3.2 1B Instruct 8-bit model',
    maxTokens: 8192,
    thumbnailUrl: inferencenetLogo,
  },
  {
    id: 'meta-llama/llama-3.2-3b-instruct/fp-8',
    name: 'llama-3.2-3b-instruct/fp-8 (inference.net)',
    provider: 'inferencenet',
    description: 'Meta Llama 3.2 3B Instruct 8-bit model',
    maxTokens: 8192,
    thumbnailUrl: inferencenetLogo,
  },
  {
    id: 'meta-llama/llama-3.2-11b-instruct/fp-8',
    name: 'llama-3.2-11b-instruct/fp-8 (inference.net)',
    provider: 'inferencenet',
    description: 'Meta Llama 3.2 11B Instruct 8-bit model',
    maxTokens: 8192,
    thumbnailUrl: inferencenetLogo,
  },
  {
    id: 'meta-llama/llama-3.1-70b-instruct/fp-8',
    name: 'llama-3.1-70b-instruct/fp-8 (inference.net)',
    provider: 'inferencenet',
    description: 'Meta Llama 3.1 70B Instruct 8-bit model',
    maxTokens: 8192,
    thumbnailUrl: inferencenetLogo,
  },
  {
    id: 'mistralai/mistral-nemo-12b-instruct/fp-8',
    name: 'mistral-nemo-12b-instruct/fp-8 (inference.net)',
    provider: 'inferencenet',
    description: 'Mistral Nemo 12B Instruct 8-bit model',
    maxTokens: 8192,
    thumbnailUrl: inferencenetLogo,
  },
  {
    id: 'deepseek-reasoner',
    name: 'deepseek-reasoner (deepseek)',
    provider: 'deepseek',
    description:
      'DeepSeek Reasoner (Deepseek-R1) is a large language model with advanced reasoning capabilities',
    maxTokens: 8192,
    thumbnailUrl: deepseekLogo,
  },
  {
    id: 'deepseek-chat',
    name: 'deepseek-chat (deepseek)',
    provider: 'deepseek',
    description: 'DeepSeek V3 Chat is a large language model with advanced capabilities',
    maxTokens: 8192,
    thumbnailUrl: deepseekLogo,
  },
  // {
  //   id: 'sonar-pro',
  //   name: 'perplexity-sonar-pro',
  //   provider: 'perplexity',
  //   description: 'Perplexity Sonar Pro - Most advanced model with web search capabilities',
  //   maxTokens: 8192,
  //   thumbnailUrl: TODO
  // },
  // {
  //   id: 'sonar',
  //   name: 'perplexity-sonar',
  //   provider: 'perplexity',
  //   description: 'Perplexity Sonar - Advanced model with web search capabilities',
  //   maxTokens: 8192,
  //   thumbnailUrl: TODO
  // },
  {
    id: 'chatgpt-4o-latest',
    name: 'chatgpt-4o-latest (openai)',
    provider: 'openai',
    description: 'Latest most capable GPT 4o model for complex tasks',
    maxTokens: 8192,
    thumbnailUrl: openaiLogo,
  },
  {
    id: 'gpt-4o',
    name: 'gpt-4o (openai)',
    provider: 'openai',
    description: 'Most capable GPT 4o model for complex tasks',
    maxTokens: 8192,
    thumbnailUrl: openaiLogo,
  },
  {
    id: 'gpt-4o-mini',
    name: 'gpt-4o-mini (openai)',
    provider: 'openai',
    description: 'Smallest GPT 4o model for complex tasks',
    maxTokens: 8192,
    thumbnailUrl: openaiLogo,
  },
  {
    id: 'o1-mini',
    name: 'o1-mini (openai)',
    provider: 'openai',
    description: 'Smallest O1 model for complex tasks',
    maxTokens: 8192,
    thumbnailUrl: openaiLogo,
  },
  {
    id: 'o1',
    name: 'o1 (openai)',
    provider: 'openai',
    description: "OpenAI's O1 model for complex tasks",
    maxTokens: 8192,
    thumbnailUrl: openaiLogo,
  },
  {
    id: 'claude-3-5-sonnet-latest',
    name: 'claude-3-5-sonnet-latest (anthropic)',
    provider: 'anthropic',
    description:
      "Anthropic's Claude 3.5 Sonnet Latest - Powerful language model with enhanced reasoning",
    maxTokens: 200000,
    thumbnailUrl: anthropicLogo,
  },
  {
    id: 'claude-3-opus-latest',
    name: 'claude-3-opus-latest (anthropic)',
    provider: 'anthropic',
    description:
      "Anthropic's Claude 3 Opus Latest - Powerful language model with enhanced reasoning",
    maxTokens: 200000,
    thumbnailUrl: anthropicLogo,
  },
  {
    id: 'grok-2-1212',
    name: 'grok-2-1212 (xai)',
    provider: 'xai',
    description: 'Latest Grok model with enhanced capabilities',
    maxTokens: 131072,
    thumbnailUrl: xaiLogo,
  },
  {
    id: 'grok-2-vision-1212',
    name: 'grok-2-vision-1212 (xai)',
    provider: 'xai',
    description: 'Latest Grok 2 Vision model with enhanced capabilities',
    maxTokens: 8192,
    thumbnailUrl: xaiLogo,
  },
  {
    id: 'gemini-2.0-flash-exp',
    name: 'gemini-2.0-flash-exp (google)',
    provider: 'google',
    description:
      'Next generation features, speed, and multimodal generation for a diverse variety of tasks',
    maxTokens: 1048576,
    thumbnailUrl: googleLogo,
  },
  {
    id: 'gemini-1.5-flash',
    name: 'gemini-1.5-flash (google)',
    provider: 'google',
    description: 'Fast and versatile performance across a diverse variety of tasks',
    maxTokens: 1048576,
    thumbnailUrl: googleLogo,
  },
  {
    id: 'gemini-1.5-flash-8b',
    name: 'gemini-1.5-flash-8b (google)',
    provider: 'google',
    description: 'High volume and lower intelligence tasks',
    maxTokens: 1048576,
    thumbnailUrl: googleLogo,
  },
  {
    id: 'gemini-1.5-pro',
    name: 'gemini-1.5-pro (google)',
    provider: 'google',
    description: 'Complex reasoning tasks requiring more intelligence',
    maxTokens: 2097152,
    thumbnailUrl: googleLogo,
  },
  {
    id: 'llama-3.3-70b-versatile',
    name: 'llama-3.3-70b-versatile (groq)',
    provider: 'groq',
    description: 'Latest Meta Llama 3.3 70B model optimized for speed by Groq',
    maxTokens: 128000,
    thumbnailUrl: groqLogo,
  },
  {
    id: 'llama-3.2-90b-vision-preview',
    name: 'llama-3.2-90b-vision-preview (groq)',
    provider: 'groq',
    description: 'Latest Meta Llama 3.2 90B model optimized for vision by Groq',
    maxTokens: 128000,
    thumbnailUrl: groqLogo,
  },
  {
    id: 'deepseek-r1-distill-llama-70b',
    name: 'deepseek-r1-distill-llama-70b (groq)',
    provider: 'groq',
    description: 'Latest DeepSeek R1 Distill Llama 70B model',
    maxTokens: 128000,
    thumbnailUrl: groqLogo,
  },
  {
    id: 'meta-llama/llama-3.1-405b',
    name: 'meta-llama/llama-3.1-405b (openrouter)',
    provider: 'openrouter',
    description: 'Most capable Meta Llama 3.1 405B model via OpenRouter',
    maxTokens: 131072,
    thumbnailUrl: openrouterLogo,
  },
  {
    id: 'nousresearch/hermes-3-llama-3.1-405b',
    name: 'nousresearch/hermes-3-llama-3.1-405b (openrouter)',
    provider: 'openrouter',
    description: 'Latest Hermes 3 Llama 3.1 405B model via OpenRouter',
    maxTokens: 131072,
    thumbnailUrl: openrouterLogo,
  },
  {
    id: 'deepseek/deepseek-chat',
    name: 'deepseek-chat (openrouter)',
    provider: 'openrouter',
    description: 'Latest DeepSeek V3 Chat model via OpenRouter',
    maxTokens: 64000,
    thumbnailUrl: openrouterLogo,
  },
  {
    id: 'deepseek/deepseek-r1',
    name: 'deepseek-r1 (openrouter)',
    provider: 'openrouter',
    description: 'Latest DeepSeek R1 model via OpenRouter',
    maxTokens: 64000,
    thumbnailUrl: openrouterLogo,
  },
  {
    id: 'qwen-max',
    name: 'qwen-max (alibabacloud)',
    provider: 'alibabacloud',
    description: 'Latest Qwen Max model via Alibaba Cloud',
    maxTokens: 32768,
    thumbnailUrl: alibabacloudLogo,
  },
  {
    id: 'qwen-plus',
    name: 'qwen-plus (alibabacloud)',
    provider: 'alibabacloud',
    description: 'Latest Qwen Plus model via Alibaba Cloud',
    maxTokens: 131072,
    thumbnailUrl: alibabacloudLogo,
  },
  {
    id: 'qwen-turbo',
    name: 'qwen-turbo (alibabacloud)',
    provider: 'alibabacloud',
    description: 'Latest Qwen Turbo model via Alibaba Cloud',
    maxTokens: 1000000,
    thumbnailUrl: alibabacloudLogo,
  },
  // {
  //   id: 'meta/llama-3.1-405b-instruct',
  //   name: 'meta/llama-3.1-405b-instruct (nvidia)',
  //   provider: 'nvidia',
  //   description: 'Latest Meta Llama 3.1 405B Instruct model via Nvidia NIMs',
  //   maxTokens: 128000,
  //   thumbnailUrl: nvidiaLogo,
  // }
];
